### ISSUE TITLE
Integrate a smtpd in order to send mail from localhost

### ISSUE THREAD

**Issue by mrueg** [Drillster/drone-email#15]
It would be nice if the plugin supports sending from a smtp server spun up locally inside the container as well.
This could be useful if it needs to be integrated into golang: https://github.com/flashmob/go-guerrilla/wiki/Using-as-a-package

**Comment by mjwwit** [comment]
Drone plugins are supposed to be as simple and lightweight as possible. Spinning up an SMTP server just to send a build notification mail sounds like overkill to me. In my opinion, the SMTP server doesn't belong in the plugin container, but should exist as a separate one.

So, instead of integrating the SMTP server into drone-email, you should be looking into running an SMTP server in a separate container and connecting to that container using the drone-email plugin.

**Comment by tboerger** [comment]
And in worst case everybody is encouraged to fork plugins and add functionality that doesn't make it into the existing plugins.

**Comment by mjwwit** [comment]
I'll close this now, as I don't think it should be a part of this plugin.
